import os
import re
import json
import math
from groq import Groq
from dotenv import load_dotenv

# Load env variables
load_dotenv()

# Initialize Groq client
# Fallback to None if not set (for testing or if key is provided at startup)
groq_api_key = os.getenv("GROQ_API_KEY")
client = Groq(api_key=groq_api_key) if groq_api_key else None

def evaluate_llm_signal(text):
    """
    Evaluates the probability of the text being AI-generated using llama-3.3-70b-versatile.
    Returns:
        tuple: (score [0.0 - 1.0], explanation [str])
    """
    if not client:
        return 0.5, "Groq client not initialized. GROQ_API_KEY is missing."
    
    if not text.strip():
        return 0.0, "Empty text."

    system_prompt = (
        "You are an expert AI content detection assistant. Analyze the input text and assess "
        "the probability that it was generated by an AI language model (e.g., ChatGPT, Claude, LLaMA) "
        "versus being written by a human. Respond ONLY with a valid JSON object containing: \n"
        "- 'ai_probability': a float between 0.0 (clearly human-written) and 1.0 (clearly AI-generated).\n"
        "- 'explanation': a short sentence explaining the key semantic or structural indicators found.\n\n"
        "Do not include any formatting, markdown markers (like ```json), or extra text outside the JSON object. "
        "IMPORTANT: Highly formal or academic writing style alone should not result in a high score; look for "
        "semantic homogeneity, repetitive transition words (e.g., 'furthermore', 'it is important to note'), "
        "and lack of personal/contextual irregularities."
    )

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Analyze this text:\n\n{text}"}
            ],
            response_format={"type": "json_object"},
            temperature=0.1
        )
        
        result_json = json.loads(response.choices[0].message.content)
        score = float(result_json.get("ai_probability", 0.5))
        explanation = result_json.get("explanation", "Completed LLM semantic analysis.")
        # Clamp score between 0.0 and 1.0
        score = max(0.0, min(1.0, score))
        return score, explanation
    except Exception as e:
        # Graceful fallback in case of API issues
        return 0.5, f"Groq API error occurred: {str(e)}"

def evaluate_stylometric_signal(text):
    """
    Calculates a stylometric heuristic score based on sentence length variance,
    Type-Token Ratio (TTR), and punctuation density.
    Returns:
        float: A score from 0.0 (likely human/highly variable) to 1.0 (likely AI/highly uniform)
    """
    cleaned_text = text.strip()
    if not cleaned_text:
        return 0.0

    # 1. Split into words and tokens
    words = re.findall(r'\b\w+\b', cleaned_text.lower())
    if not words:
        return 0.5
        
    total_words = len(words)

    # 2. Type-Token Ratio (Vocabulary Diversity)
    # TTR = unique words / total words
    unique_words = len(set(words))
    ttr = unique_words / total_words

    # 3. Sentence Length Variance (Burstiness)
    # Split sentences using common punctuation marks followed by spaces or end-of-line
    sentences = re.split(r'[.!?]+(?:\s+|$)', cleaned_text)
    # Filter out empty sentences
    sentences = [s.strip() for s in sentences if s.strip()]
    
    sentence_lengths = []
    for s in sentences:
        s_words = re.findall(r'\b\w+\b', s)
        if s_words:
            sentence_lengths.append(len(s_words))
            
    num_sentences = len(sentence_lengths)

    # Compute sentence length variance
    if num_sentences > 1:
        mean_len = sum(sentence_lengths) / num_sentences
        variance = sum((l - mean_len) ** 2 for l in sentence_lengths) / (num_sentences - 1)
    else:
        # Fallback if text is too short or lacks sentence boundaries
        variance = None

    # 4. Punctuation Density
    # Punctuation marks divided by total character length
    punctuation = re.findall(r'[,;:\-\(\)\"\'\?!]', cleaned_text)
    punct_density = len(punctuation) / len(cleaned_text) if len(cleaned_text) > 0 else 0.0

    # 5. Score Translation & Combination
    # Stylometric features tend to be highly uniform in AI texts:
    # - Sentence length variance is low (AI writes sentences of standard length, e.g., var < 15)
    # - Type-Token Ratio is standard (AI uses middle-of-the-road vocab diversity, TTR around 0.55-0.70 for medium texts)
    # - Punctuation is regular.
    
    # Sentence length variance contribution:
    # If variance is None (short text), we cannot assess burstiness. We default to neutral (0.5).
    # If variance is low (<10), it's highly uniform (AI-like, score close to 1.0).
    # If variance is high (>40), it's bursty (human-like, score close to 0.0).
    if variance is not None:
        # Map variance [5, 40] to score [1.0, 0.0]
        var_score = 1.0 - (max(5.0, min(40.0, variance)) - 5.0) / 35.0
    else:
        var_score = 0.5

    # TTR contribution:
    # Very high TTR (>0.8 for medium text) or very low TTR (<0.4) indicates human-like extremes.
    # A standard TTR (0.55 to 0.70) is typical of AI.
    if 0.55 <= ttr <= 0.70:
        ttr_score = 0.8
    else:
        # Distance from the standard AI TTR range
        dist = min(abs(ttr - 0.55), abs(ttr - 0.70))
        ttr_score = max(0.0, 0.8 - (dist * 2.0))

    # Punctuation density contribution:
    # Typical AI punctuation density is between 0.01 and 0.025.
    if 0.01 <= punct_density <= 0.025:
        punct_score = 0.7
    else:
        punct_score = 0.3

    # Combine stylometric indicators:
    # If text is very short (< 30 words), heuristics are highly unreliable, so pull to 0.5
    if total_words < 30:
        raw_heuristics_score = 0.5
    else:
        # Weighted average of heuristics
        raw_heuristics_score = (0.5 * var_score) + (0.3 * ttr_score) + (0.2 * punct_score)

    return max(0.0, min(1.0, raw_heuristics_score))

def get_transparency_label(verdict, confidence):
    """
    Generates a user-facing transparency label text and header based on verdict and confidence.
    """
    confidence_pct = int(confidence * 100)
    
    if verdict == "likely_human":
        if confidence >= 0.75:
            return {
                "header": "Verified Human-Written",
                "text": f"Provenance Guard: Verified Human-Written. This content shows strong indicators of human authorship, exhibiting rich sentence structure and organic stylistic variance. Confidence: High (Calibrated at {confidence_pct}%)."
            }
        else:
            return {
                "header": "Indeterminate / Mixed Style",
                "text": f"Provenance Guard: Indeterminate/Mixed Signals. Our analysis did not find clear evidence to classify this content as either fully human-written or AI-generated. This often occurs when writing is highly structured or contains a blend of styles. Confidence: Low/Uncertain. If you are the creator and wish to clarify your process, you may submit an appeal."
            }
            
    elif verdict == "likely_ai":
        if confidence >= 0.75:
            return {
                "header": "AI-Generated Content",
                "text": f"Provenance Guard: AI-Generated Content. This content matches patterns commonly associated with AI models. Confidence: High (Calibrated at {confidence_pct}%). This classification is based on stylistic and semantic analysis. If you are the creator and believe this is an error, you may file an appeal."
            }
        else:
            return {
                "header": "Indeterminate / Mixed Style",
                "text": f"Provenance Guard: Indeterminate/Mixed Signals. Our analysis did not find clear evidence to classify this content as either fully human-written or AI-generated. This often occurs when writing is highly structured or contains a blend of styles. Confidence: Low/Uncertain. If you are the creator and wish to clarify your process, you may submit an appeal."
            }
            
    else: # verdict == "uncertain"
        return {
            "header": "Indeterminate / Mixed Style",
            "text": f"Provenance Guard: Indeterminate/Mixed Signals. Our analysis did not find clear evidence to classify this content as either fully human-written or AI-generated. This often occurs when writing is highly structured or contains a blend of styles. Confidence: Low/Uncertain. If you are the creator and wish to clarify your process, you may submit an appeal."
        }

def combine_signals(llm_score, styl_score):
    """
    Combines LLM score and Stylometric score.
    Returns:
        tuple: (verdict [str], confidence [float], combined_score [float])
    """
    # 70% LLM, 30% Heuristics
    combined_score = 0.70 * llm_score + 0.30 * styl_score
    
    # Verdict boundaries:
    # likely_human: combined_score <= 0.30
    # likely_ai: combined_score >= 0.75
    # uncertain: 0.30 < combined_score < 0.75
    if combined_score <= 0.30:
        verdict = "likely_human"
        # Scale to [0.70, 1.00] from score [0.30, 0.00]
        # score = 0.30 => confidence = 0.70
        # score = 0.00 => confidence = 1.00
        confidence = 1.0 - combined_score
        
    elif combined_score >= 0.75:
        verdict = "likely_ai"
        # Scale to [0.75, 1.00] from score [0.75, 1.00]
        confidence = combined_score
        
    else:
        verdict = "uncertain"
        # Center is at 0.525. Calculate uncertainty based on distance to 0.525.
        # Max distance is 0.225 (at 0.30 or 0.75).
        # We define confidence of being uncertain as: 1.0 - (dist / 0.225)
        # Closer to center => lower confidence in classification (higher uncertainty).
        dist = abs(combined_score - 0.525)
        uncertainty = 1.0 - (dist / 0.225)
        confidence = 1.0 - uncertainty # This will yield confidence values ranging from 0.0 (near 0.525) to 1.0 (near boundaries)
        # Wait, let's make confidence represent the confidence in the verdict.
        # If the verdict is uncertain, the confidence of the classification is low.
        # Let's scale confidence to reflect low confidence, e.g. [0.0, 0.70].
        # If we use: confidence = 0.70 - (uncertainty * 0.70)
        # That means at center (uncertainty = 1), confidence = 0.0.
        # At boundary (uncertainty = 0), confidence = 0.70.
        confidence = 0.70 * (dist / 0.225)
        
    return verdict, round(confidence, 4), round(combined_score, 4)
